name: tpm20softwaresimulator
version: '1119'
summary: TPM 2.0 Simulator
description: |
  Snap package for IBM's software TPM 2.0 simulator.
  Based on the TPM 2.0 specification's source code donated by Microsoft,
  with additional files to complete the implementation donated by Ken Goldman.
  Original homepage is at https://sourceforge.net/projects/ibmswtpm2/
grade: devel
confinement: strict
apps:
  tpm20softwaresimulator:
    command: tpm_server
    plugs: [home, network-bind]
parts:
  tpm2-simulator:
    plugin: make
    build-packages:
      - gcc
      - libc6-dev
      - libssl-dev
      - make
    source: src
    organize:
      build/src/tpm_server: tpm_server
    artifacts:
      - build/src/tpm_server
    prime:
      - -build
